export const orderBlockSynonyms = [
  "order block",
  "order blocks",
  "orderblock",
  "orderblocks",
  "ob",
  "obs",
  "demand zone",
  "demand zones",
  "supply zone",
  "supply zones",
  "supply and demand",
  "supply & demand",
  "unmitigated zone",
  "unmitigated zones",
  "unmitigated order block",
  "unmitigated order blocks",
  "unmitigated supply",
  "unmitigated demand",
  "unmitigated",
  "institutional zone",
  "institutional order block",
  "poi",
  "point of interest"
];
